export function createAlphaSettings(options?: any): {
    blendCutoff: any;
    costumeCutout: boolean;
    coverageMode: any;
    cutoutCutoff: any;
    ditherOpacity: any;
    enabled: boolean;
    expressionTokenCutout: boolean;
    eyeHighlightOrder: any;
    eyeOrder: any;
    faceCutout: boolean;
    hairCutout: boolean;
    mapTransparentCutout: boolean;
    overlayDepthWrite: boolean;
    featuresOverHairDepth: any;
    overlayOrder: any;
    preserveSourceAlphaTest: boolean;
    scleraOrder: any;
    skinCutout: boolean;
    sortOverlays: boolean;
    sourceAlphaMapCutout: boolean;
    sourceTransparentCutout: boolean;
    transparentOverlayBlend: boolean;
    transparentOpacityThreshold: any;
};
export function sourceOpacity(mat: any): any;
export function declaresAlphaBlend(mat: any): boolean;
export function usesAlphaCutout(mat: any, roleInfo: any, settings?: {
    blendCutoff: any;
    costumeCutout: boolean;
    coverageMode: any;
    cutoutCutoff: any;
    ditherOpacity: any;
    enabled: boolean;
    expressionTokenCutout: boolean;
    eyeHighlightOrder: any;
    eyeOrder: any;
    faceCutout: boolean;
    hairCutout: boolean;
    mapTransparentCutout: boolean;
    overlayDepthWrite: boolean;
    featuresOverHairDepth: any;
    overlayOrder: any;
    preserveSourceAlphaTest: boolean;
    scleraOrder: any;
    skinCutout: boolean;
    sortOverlays: boolean;
    sourceAlphaMapCutout: boolean;
    sourceTransparentCutout: boolean;
    transparentOverlayBlend: boolean;
    transparentOpacityThreshold: any;
}, coverage?: any): any;
export function usesAlphaBlend(mat: any, roleInfo: any, settings?: {
    blendCutoff: any;
    costumeCutout: boolean;
    coverageMode: any;
    cutoutCutoff: any;
    ditherOpacity: any;
    enabled: boolean;
    expressionTokenCutout: boolean;
    eyeHighlightOrder: any;
    eyeOrder: any;
    faceCutout: boolean;
    hairCutout: boolean;
    mapTransparentCutout: boolean;
    overlayDepthWrite: boolean;
    featuresOverHairDepth: any;
    overlayOrder: any;
    preserveSourceAlphaTest: boolean;
    scleraOrder: any;
    skinCutout: boolean;
    sortOverlays: boolean;
    sourceAlphaMapCutout: boolean;
    sourceTransparentCutout: boolean;
    transparentOverlayBlend: boolean;
    transparentOpacityThreshold: any;
}): boolean;
export function alphaTestForMaterial(mat: any, roleInfo: any, settings?: {
    blendCutoff: any;
    costumeCutout: boolean;
    coverageMode: any;
    cutoutCutoff: any;
    ditherOpacity: any;
    enabled: boolean;
    expressionTokenCutout: boolean;
    eyeHighlightOrder: any;
    eyeOrder: any;
    faceCutout: boolean;
    hairCutout: boolean;
    mapTransparentCutout: boolean;
    overlayDepthWrite: boolean;
    featuresOverHairDepth: any;
    overlayOrder: any;
    preserveSourceAlphaTest: boolean;
    scleraOrder: any;
    skinCutout: boolean;
    sortOverlays: boolean;
    sourceAlphaMapCutout: boolean;
    sourceTransparentCutout: boolean;
    transparentOverlayBlend: boolean;
    transparentOpacityThreshold: any;
}, coverage?: any): number;
export function resolveAlphaForMaterial(settings: any, mat: any, roleInfo: any, coverage?: any): {
    alphaBlend: boolean;
    alphaCutout: boolean;
    alphaTest: any;
    coverage: "soft";
    depthWrite: any;
    opacity: any;
    textureAlpha: number;
    transparent: boolean;
} | {
    alphaBlend: boolean;
    alphaCutout: any;
    alphaTest: number;
    coverage: any;
    depthWrite: any;
    opacity: any;
    textureAlpha: number;
    transparent: boolean;
};
export function materialAlphaDrawOrder(settings: any, mat: any, roleInfo: any): any;
export const ALPHA_COVERAGE_MODES: Readonly<{
    auto: "auto";
    trust: "trust";
}>;
export const DEFAULT_ALPHA_SETTINGS: Readonly<{
    blendCutoff: 0.02;
    costumeCutout: true;
    coverageMode: "auto";
    cutoutCutoff: 0.35;
    ditherOpacity: 1;
    enabled: true;
    expressionTokenCutout: true;
    eyeHighlightOrder: 12;
    eyeOrder: 11;
    faceCutout: true;
    featuresOverHairDepth: 0.03;
    hairCutout: true;
    mapTransparentCutout: true;
    overlayDepthWrite: false;
    overlayOrder: 20;
    preserveSourceAlphaTest: true;
    scleraOrder: 10;
    skinCutout: true;
    sortOverlays: true;
    sourceAlphaMapCutout: true;
    sourceTransparentCutout: true;
    transparentOverlayBlend: true;
    transparentOpacityThreshold: 0.999;
}>;
