export class WaterDynamics {
    constructor(surface: any, options?: {});
    surface: any;
    isWaterDynamics: boolean;
    options: {};
    mode: any;
    time: number;
    columns: any;
    rows: any;
    state: Float32Array<ArrayBuffer>;
    normals: Float32Array<ArrayBuffer>;
    history: Float32Array<ArrayBuffer>;
    foamCoordinates: Float32Array<ArrayBuffer>;
    previousFoamCoordinates: Float32Array<ArrayBuffer>;
    shoreDistances: Float32Array<ArrayBuffer>;
    shoreContour: Float32Array<any>;
    causticResolution: number;
    light: Float32Array<ArrayBuffer>;
    causticWork: Float64Array<ArrayBuffer>;
    causticRegion: THREE.Vector4;
    previousFoam: Float32Array<ArrayBuffer>;
    stateAttribute: THREE.BufferAttribute<THREE.BufferAttributeEventMap>;
    normalAttribute: THREE.BufferAttribute<THREE.BufferAttributeEventMap>;
    texture: THREE.DataTexture;
    foamCoordinateTexture: THREE.DataTexture;
    causticTexture: THREE.DataTexture;
    spectrum: WaterSpectralOcean;
    normalSpectrum: WaterSpectralOcean;
    detailSpectrum: WaterDetailSpectrum;
    normalTextures: THREE.DataTexture[];
    gridSignature: string;
    reference: boolean;
    paused: boolean;
    pendingStep: number;
    sampleScratch: {};
    settingsSignature: string;
    getRegion(out?: THREE.Vector4): THREE.Vector4;
    rebuild(): void;
    foamParticles: any;
    renderExtension: any;
    x: any;
    z: any;
    level: any;
    dx: number;
    dz: number;
    minX: number;
    minZ: number;
    bed: any;
    hydro: WaterHydrodynamics;
    interactions: WaterHydrodynamics;
    warmupRemaining: number;
    boundary(side: any, x: any, z: any, time: any, ghost: any): boolean;
    update(delta: any): void;
    incidentWaves: {
        dirX: number;
        dirZ: number;
        omega: number;
        waveNumber: number;
        amplitude: number;
        phase: number;
        steepness: number;
        crestWeight: number;
    }[];
    updateShoreContour(): void;
    updateFoamCoordinates(dt: any): void;
    updateCaustics(): void;
    sample(x: any, z: any, out?: {}): {};
    impulse(x: any, z: any, strength: any, radius: any): void;
    shoreEdgeAt(x?: number, minimumDepth?: number): number;
    diagnostics(): {
        time: number;
        steps: number;
        volume: number;
        boundaryVolume: number;
        massError: number;
        roundoffVolume: number;
        minDepth: any;
    } | {
        time: number;
        model: string;
        bands: number;
        peakLength: number;
    };
    dispose(): void;
}
import * as THREE from 'three';
import { WaterSpectralOcean } from './waterSpectralOcean.js';
import { WaterDetailSpectrum } from './waterDetailSpectrum.js';
import { WaterHydrodynamics } from './waterHydrodynamics.js';
