/** The shading role of a classified material. */
export function characterRoleKey(roleInfo: any): "skin" | "face" | "hair" | "eye" | "metal" | "cloth";
export function cameraShadowDirection(character: any): THREE.Vector3;
/**
 * Uniform values for one material. `context` describes the material:
 * `{ role, roleWeights, hasSpecularMask, paintedEyeHighlights, isSclera,
 *    hasFaceMap, baseSaturation }`.
 */
export function resolveCharacterParameters(settings: any, context?: {}): {
    lightEnabled: number;
    sunMax: any;
    sunTint: any;
    lightMaxTint: any;
    skyFloor: any;
    skyMax: any;
    shadeSkyTint: any;
    shadowSkyTint: any;
    cameraLightStrength: any;
    cameraLightDirection: number[];
    maxSunElevationSin: number;
    hemisphereByNormal: number;
    localLightIntensity: any;
    localLightMax: any;
    localLightSoftness: any;
    highlightShadowFloor: any;
    antiAlias: any;
    autoBiasStart: any;
    autoBiasEnd: number;
    lightingMapChannel: number[];
    lightingMapScale: any;
    lightingMapPivot: any;
    bandWidth: any;
    faceMapStrength: any;
    faceMapSoftness: any;
    faceMapOffset: any;
    faceMapMirror: number;
    faceMapMidU: any;
    faceNormalAmount: any;
    faceNormalRoundness: any;
    faceHeadTracked: number;
    noseStrength: any;
    noseSize: any;
    noseTint: any;
    eyeWhiteStrength: any;
    eyeWhiteDepth: any;
    eyeWhiteTint: any;
    characterShadowNormalBias: any;
    characterShadowDepthBias: any;
    characterShadowSoftness: any;
    screenShadowWidth: any;
    rimMode: number;
    rimWidth: any;
    rimThreshold: any;
    rimSoftness: any;
    rimTint: any;
    rimAlbedoMix: any;
    rimInShadow: any;
    rimFadeStart: any;
    rimFadeEnd: number;
    specularInShadow: any;
    specularMaskChannel: number[];
    specularMaskStrength: any;
    hairRingIntensity: any;
    hairRingWidth: any;
    hairRingOffset: any;
    hairRingStrands: any;
    hairRingJitter: any;
    hairRingLean: any;
    hairRingShadowFloor: any;
    sheerColor: any;
    sheerIntensity: any;
    sheerPower: any;
    outlineMaxWidth: any;
    outlineScreenSpace: any;
    outlineReferenceUnits: number;
    outlineFadeDistance: any;
    inkHueShift: any;
    outlineFaceDepthPush: any;
    outlineWidthMapChannel: number[];
    outlineVertexColorChannel: number[];
    normalStrength: any;
    normalScale: any;
    aoStrength: any;
    emissiveTint: any;
    emissiveStrength: any;
    matcapStrength: any;
    detailRepeat: any;
    detailStrength: any;
    roughnessStrength: any;
    metalnessStrength: any;
    specularColorStrength: any;
    baseSaturation: any;
    ditherOpacity: any;
    overHairDepth: any;
};
export const CHARACTER_ROLE_KEYS: readonly string[];
export const ROLE_WEIGHT_SUFFIXES: Readonly<{
    face: "Face";
    hair: "Hair";
    skin: "Skin";
}>;
export const ROLE_PARAMETER_NAMES: readonly string[];
import * as THREE from 'three';
